INSERT INTO roles(name)
SELECT 'ROLE_USER' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ROLE_USER');

INSERT INTO roles(name)
SELECT 'ROLE_ADMIN' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ROLE_ADMIN');
