export const ActionTypes = {
    GET_CART_ITEMS_NUMBERS: "GET_CART_ITEMS_NUMBERS",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",    
    EMPTY_CART: "EMPTY_CART",
    DECREASE_QUANTITY: "DECREASE_QUANTITY",
    GET_TOTAL_CART_AMOUNT: "GET_TOTAL_CART_AMOUNT",
    SAVE_FOR_LATER: "SAVE_FOR_LATER",
    MOVE_TO_CART: "MOVE_TO_CART",
    DELETE_FROM_SAVED: "DELETE_FROM_SAVED"
}